# NOTE: update this with your service name
service: outcom-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
  # vpc:
  #   securityGroupIds:
  #     - sg-0c5fad3fa58d44208
  #   subnetIds:
  #     - subnet-9bba64b7
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - "ec2:CreateNetworkInterface"
  #     Resource: "*"
  timeout: 20
  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - dynamodb:DescribeTable
  #       - dynamodb:Query
  #       - dynamodb:Scan
  #       - dynamodb:GetItem
  #       - dynamodb:PutItem
  #       - dynamodb:UpdateItem
  #       - dynamodb:DeleteItem
  #     Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  # Tag: Student
  studentUploadImage:
    handler: studentUploadImage.main
    events:
      - http:
          path: student/{id}/uploadImage
          method: post
          cors: true
          # authorizer: aws_iam
  createStudent:
    handler: createStudent.main
    events:
      - http:
          path: student
          method: post
          cors: true
          # authorizer: aws_iam
  getStudentById:
    handler: getStudentById.main
    events:
      - http:
          path: student/{id}
          method: get
          cors: true
          #authorizer: aws_iam                  
  updateStudent:
    handler: updateStudent.main
    events:
      - http:
          path: student
          method: put
          cors: true
          # authorizer: aws_iam

  # Tag: Teacher
  getTeacherById:
    handler: getTeacherById.main
    events:
      - http:
          path: teacher/{id}
          method: get
          cors: true
          #authorizer: aws_iam  
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /class
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
  listTeacher:
    # Defines an HTTP API endpoint that calls the main function in list.js
    # - path: url path is /teacher
    # - method: GET request
    handler: listTeacher.main
    events:
      - http:
          path: teacher
          method: get
          cors: true
          #authorizer: aws_iam

  # Tag: Class
  createClass:
    handler: createClass.main
    events:
      - http:
          path: class
          method: post
          cors: true
          # authorizer: aws_iam
  getClassById:
    handler: getClassById.main
    events:
      - http:
          path: class/{id}
          method: get
          cors: true
          #authorizer: aws_iam            
  updateClass:
    handler: updateClass.main
    events:
      - http:
          path: class
          method: put
          cors: true
          # authorizer: aws_iam          
# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}